"""empty message

Revision ID: cbd2db54c374
Revises: f9a8bd977d73
Create Date: 2020-04-15 09:37:45.165543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd2db54c374'
down_revision = 'f9a8bd977d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
